[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.4"
edition = "2024"
license = "MIT"
description = "A modern and fast package manager for Arch-based systems"
authors = ["Denis Salmanovich"]
readme = "README.md"

[workspace.dependencies]
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
tar = "0.4"
rayon = "1"
owo-colors = "4"
ureq = { version = "3", default-features = false, features = ["native-tls"] }
sha2 = "0.11"
indicatif = "0.18"
tempfile = "3"
zstd = "0.14"
xz2 = "0.1"
md5 = "0.8"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
